### ISSUE TITLE
What is the correct way to test state dependant "connected" HOC's

### ISSUE THREAD

**Issue by PavelPolyakov** [airbnb/enzyme#1025]
There are several issues where people ask how to test `connected` components, as it's not possible to `setState` for them. The answer is - we need export pure and connected components separately.
([here](https://github.com/airbnb/enzyme/issues/98) and [here](https://github.com/airbnb/enzyme/issues/431), for example)

However, there is another situation, which I've reproduced in this repository:
https://github.com/PavelPolyakov/enzyme-HOC-setState

Imagine we have a HOC which needs to grab some information from the redux store and attach it to the `WrappedComponent`. In the examples case it attaches the pokemon info:
https://github.com/PavelPolyakov/enzyme-HOC-setState/blob/master/src/appHOC.js

At the same time, there is a `state` condition in the `HOC` code itself, let's say we start some procedure on `componentWillMount` and don't want to show anything till this procedure is done. The procedure is asynchronous.

It's not possible to do neither:
```
root.find('AppHOC').setState({});
```
nor
```
root.find('AppHOC').state();
```
The latest could be very useful, so it's possible to write a proper async wait for the state.

What is the correct way to test it? Let's say I want to mock the asynchronous procedure during the tests. However, I'm not able to `setState` on the component directly, because this is not a root component. From the other point - I can not export it as a pure component, as it depends on the `WrappedComponent`.

As a dirty solution, it is possible to put your `expect` inside the `setTimeout`, however, it means we wait for the max time:
https://github.com/PavelPolyakov/enzyme-HOC-setState/blob/master/src/__tests__/appHOC.test.js

@ljharb , what would be the suggested way to overcome this situation using `enzyme` ?

Regards,

**Comment by ljharb** [comment]
You do not need to export the inner component at all, and should definitely never change your code just for testing.

All of your tests for the inner component should wrap the outer component, and use `.dive()`. That way, you're exercising the wrapper every time, but you're able to directly interact with the inner component.

**Comment by PavelPolyakov** [comment]
hi @ljharb ,

Thanks for the quick answer.
I found you mentioning dive in the issues, however, if I understand correctly - `dive` can be used only with shallow rendering: https://github.com/airbnb/enzyme/blob/master/docs/api/ShallowWrapper/dive.md .

In my example I use `mount`.

In the documentation it is stated:
> Full DOM rendering is ideal for use cases where you have components that may interact with DOM APIs, or may require the full lifecycle in order to fully test the component (i.e., componentDidMount etc.)

Indeed I heavy rely on the lifecycle hooks and store updates. I've tried to swap `mount` with `shallow` in the real world example and it doesn't work, as `store` changes which I do were not applied (component properties were not updated).

```javascript
const ah = wrapper.find('AppHOC').dive();
ah.setState({isRegistered: true});

storeState.form['pokemon:charmander'] = true;
ah.setProps({run: 1});

// expect() that something will happen during componentWillReceiveProps
```

What would the flow of testing the full lifecycle components?

Regards,

**Comment by ljharb** [comment]
I'm mobile atm so I can't give you a full example, but if you're using mount, you should only be passing props at the top of the tree. In general tho, you should prefer shallow to mount - if you need the experimental lifecycle option to shallow, that's fine too.

In other words, you should be able to get very close to 100% coverage of your codebase with shallow alone (testing everything at each level) - you can even explicitly .instance().componentDidMount() etc when needed, and unit-test individual instance methods - and fall back to `mount` only when you really need to truly test post-mounting logic (which should be very rare and minimal, ideally).

**Comment by PavelPolyakov** [comment]
@ljharb 
thank you for your clarification, I'd try to migrate everything to `shallow`.
have a good weekend!

I'd appreciate in case you find spare time to quickly check my `shallow`/`mount` example tomorrow (or any other day).

Thank you for the library!

**Comment by dabit1** [comment]
I finally found a very good solution to get a wrapper from a decorated component. For shallowed components you can use `dive()` but there is no similar method for mounted components. This is the solution I did:

```javascript
const wrapper = mount(shallow(<MyComponent />).get(0))
```

Works like a charm :)

**Comment by dabit1** [comment]
@dschinkel who did say that workaround was not for intrgration tests? :) Anyway,  TDD allows integration tests and creating more unit tests than integration tests is just a recommendation. Also, TDD in react unfortunately requires to use `mount` more than I would like.

**Comment by dschinkel** [comment]
@dabit1 you don't understand TDD.  You don't need mount and should prefer shallow when you TDD.

**Comment by dabit1** [comment]
@dschinkel who the hell are you? Some kind of TDD prophet? Give me an argument instead of just saying "relies on". I do TDD in Reactjs and React Native and I know the problematic you can find out there. TDD in React is not the same than in other technologies and if you really want to specify every feature you will have to use mount in some moments.

**Comment by dschinkel** [comment]
I've done it for years.  I'm happy to discuss it.

**Comment by dabit1** [comment]
Unit tests should be the most you write. But I don't agree that if you create some small integration tests you are not doing TDD. Apart of that Enzyme and React are quite particular... And if I have to mount a component when I'm testing instead of adding extra code to the component I'm testing I definitely prefer it. It's a balance between clean and testable code.

**Comment by dschinkel** [comment]
Cool.

You must be referring to what I call "Component/Acceptance" tests (outside tests in BDD).  I still use shallow for those but that's my approach.  I've found a way to do that which works and sharing that in my course.

**Comment by dabit1** [comment]
@dschinkel yes I know Carlos Ble. I read his book several times. I started in the world of testing because of that book.
I'll read the interview later ;)

**Comment by dabit1** [comment]
About what you call "Component/Acceptance" I may agree. But they are just words. At the end TDD is creating a failure test, making it pass and refactoring. If you want to speak about details you will find different approaches from different people. However as I said before I prefer to make it as easier as possible because apart of doing testing in the right way you look for another things like clean code and a good testing architecture which a good architecture always should be easy to understand.

**Comment by dabit1** [comment]
By the way I would be happy to see your approach @dschinkel

**Comment by dabit1** [comment]
@dschinkel I subscribed on your course, I'm curious to know how you manage BDD and TDD with React. I have a test assigment from a company I applied on my github. You can take a look at README and the project itself to check how I manage BDD and TDD with React: 
https://github.com/dabit1/globalmovies

**Comment by dschinkel** [comment]
Oh hey sorry I was busy.  Thanks for subscribing.  I really want to get people to realize what a gem enzyme really is.  A lot of devs are looking for stuff that makes it easier when really, more magic is not going to help, what will is more practice with testing and enzyme.

>I'm curious to know how you manage BDD and TDD with React

I spent 1.5 years building WeDoTDD.com working night and day figuring out FE and TDD with React. When i was doing WeDoTDD.com I was not working, not getting paid, it was rough but that's how I learned it initially and tweaked my style along the way, hit all the brick walls you can probably hit with it already and found ways to do it well and get past those issues. 

I then applied that knowledge and taught developers on teams doing React on big systems such as at Fox, and other .coms.  

I've since then worked at 8th Light previously TDD'ing more on React but with GraphQL and renderProps + HOCs which I'm not too fond of because they're hard to test when they're all nested in a mess.  

I can't wait till I start using React hooks to get back to "simplicity" hopefully and thus making people realize a ton of nested HOCs isn't going to help you, breaking apart stuff will and keeping your react modules small.  

So I've practiced TDD with React + Enzyme going on 4 solid years now every day on the Job.  Done TDD for about 6 years.  

Sure I can take a look at your repo!

**Comment by dabit1** [comment]
@dschinkel Nice. I really want to check how you do it out.
Please try to reread your comments before submitting them, you are making me feel crazy since I had to reread your comment a few times hehe.

**Comment by dschinkel** [comment]
I reviewed yours.  I am not a fan of Dodd's way of doing things which is why I'm so hell bent on getting mine out and the TDD way.  He tries to say enzyme is too complicated but I think he falls short from experience.  So I don't use his `react-redux-test` and in fact some of how he's showing how he tests action creators, I do the same but my tests are even simpler.  I'm not a huge fan of mocking frameworks and mostly use custom mocks.

**Comment by dschinkel** [comment]
> About Cucumber, I really think it is important since it ensures creating a non ambiguous features. It's an efficient way to define the requirements in a clear way for technical and non technical stackholders

yea if you can get your stakeholders actually involved in writing those specs, more power to you.

**Comment by dabit1** [comment]
> yea if you can get your stakeholders actually involved in writing those specs, more power to you.
Even if you are doing a project for yourself and you are the ony one who is going to work on it it is really useful because of what Gherkin enforces to you.

**Comment by PierreTurnbull** [comment]
why is it so complicated to manipulate a non-HOC component?
I've got 3 layers on top of my component, and dabit1's solution worked great for moving past one of these, but I can't figure out how to move past the 2 others...
