### ISSUE TITLE
Wrong output from new Date() function in enzyme test

### ISSUE THREAD

**Issue by Sandeep3005** [airbnb/enzyme#1097]
I am using the enzyme for testing my react app.
Now inside my app when I am running following command I am getting below output
<br>
Inside jsx file when I do console.log for below-mentioned line

    Input  - new Date(moment().format('YYYY,MM,DD'))
    Output - Wed Aug 30 2017 00:00:00 GMT+0530 (IST)

But inside test cases when I am passing value defautlState 

    const defaultState = {
     dateToDisplay: new Date(moment().format('YYYY,MM,DD')),
    };

    it('shows slots on time scroller', () =>{
      const wrapper = shallow(<BookingDialogNew />);
      wrapper.setProps(defaultProps);
      wrapper.setState(defaultState);
    });

I am getting output - `2017-08-29T18:30:00.000Z`

Not very good with moment and date, how to get output same as in the jsx file
Are there two line are same, please guide

**Comment by aweary** [comment]
Hey, @Sandeep3005! It doesn't look like your issue has anything to do with Enzyme. As far as I can tell, you're using the moment API wrong. You should be passing a date to `moment`, not the other way around, or no date at all if you want to just use the current date.

```js
// Assumes you want to format the current date + time
moment().format('YYYY,MM,DD')
// Formats the date + time for the passed Date instance
moment(new Date('1/1/2001')).format('YYY,MM,DD')
```

The discrepancy you're seeing is due to how browsers and Node render dates differently. If you have more trouble with this I recommend referring to the [moment](https://momentjs.com/) docs, since this is unrelated to Enzyme.
