### ISSUE TITLE
Question: How can I avoid "deep diving"?

### ISSUE THREAD

**Issue by javidjamae** [airbnb/enzyme#1138]
I'm trying to be a good programmer and use HOCs to properly decouple and decompose my code. I have components that are composed like this:

```
const enhance = compose(
  connect( mapStateToProps, actions ),
  reduxForm( {
    form: 'connection',
    validate,
    onSubmit: ( val, dispatch, { navigation, connectionCreate } ) => connectionCreate( val, navigation )
  } ),
  withSpinnerOnLoading(),
)

export default enhance( AddConnectionDetailsForm )
```

The `withSpinnerOnLoading()` even has a branch in it, so to test the underlying component, I have tests that do this:

```
expect( wrapper.dive().dive().dive().dive() ).toMatchSnapshot()
```

This starts to get a little nasty. Is there any easier way to "deep dive" down to my component? I'd love to be able to do something like:

```
expect( wrapper.dive( 4 ) ).toMatchSnapshot()
```

or

```
expect( wrapper.dive( { depth = 4 } ) ).toMatchSnapshot()
```

Any suggestions?

**Comment by ljharb** [comment]
We intentionally did not include a "depth" parameter in `dive` since that would be a very brittle coupling to the number of HOCs - the only current solution is indeed multiple `.dive()` calls, which is similarly brittle, but *looks* worse, and as such, more correctly identifies a brittle scenario in code.

In React 16 and a future enzyme 3+ semver-minor, there will be an API that will allow for this in a robust way, but for now, the multiple dives are the best way (and also what Airbnb does in its many thousands of enzyme tests).

(Separately, I don't think snapshot testing is ever a good way to test code; but that's orthogonal to this issue)

**Comment by javidjamae** [comment]
@ljharb Thanks for the quick response!

> more correctly identifies a brittle scenario in code

Not sure exactly what you mean by that, but composing HOCs like that is arguably a less brittle approach (i.e. low coupling / high cohesion), not more brittle.

I'm torn on using snapshots, personally. I used to use VCR in Ruby and had a love/hate relationship with it. I started exploring using jest after reading [this argument in support of using snapshots](https://blog.callstack.io/unit-testing-react-native-with-the-new-jest-i-snapshots-come-into-play-68ba19b1b9fe) when testing React Native apps.

**Comment by ljharb** [comment]
Right, to clarify, it's not brittle in your production code, but rather in your test code.

In my experience snapshots are only useful for ensuring refactors change nothing; all other times, people just rubber stamp snapshot diffs and don't understand why the changes matter.

**Comment by bregenspan** [comment]
@javidjamae Until Enzyme adds an API for deep traversal, one approach that might work for you is this `diveTo` helper, which recursively dives until a target is found: https://gist.github.com/bregenspan/83126a50da7cf0a4d16b11499e12f7bc . Only using it for a few tests so far here at Teachers Pay Teachers, so YMMV.

**Comment by MartinDawson** [comment]
@bregenspan I had to remove the error checking in enzyme 3.0.

Also, I had to use `if (instance && shallowWrapper.name() === identifier) {` to check current node.

**Comment by yairEO** [comment]
> We intentionally did not include a "depth" parameter in `dive`...
> 
> In React 16 and a future enzyme 3+ semver-minor, there will be an API that will allow for this in a robust way, but for now, the multiple dives are the best way (and also what Airbnb does in its many thousands of enzyme tests).

5 years later, still no version `3+` (yes I know Enzyme is dead for years), no `depth` parameter and no clear docs:

![image](https://user-images.githubusercontent.com/845031/190919871-74b30b77-2fce-48d9-89b3-2af8529c9121.png)


The `Arguments` section is a complete mystery...

**Comment by ljharb** [comment]
@yairEO enzyme is not dead at all. If you want things to move faster, provide money or time, but complaining makes things move slower. Make a PR if you want the docs improved.

**Comment by yairEO** [comment]
@ljharb - complaining is the ultimate tool for improvements. The press's only job is to constantly complain to stir politicians in their seats when exposing "bad" stuff.

The public constantly riot and revolt to create change by screaming "bad bad bad".

I came here and exposed politely some incorrect stuff which were said some years ago and are 
very confusing and only wasted time for me and probably countless others.

Marking my comment as "disruptive content" makes you look identical to Russia and China, a totalitarian countries while tries their best shutting up people who says the truth.

If you want to promote freedom in the world, let people speak without silencing them, as long
as the content is within the norms of what's considered "respectable" at that moment in time.

Your claim that *"enzyme is not dead at all"* is confusing since no new release was published for years although there are hundreds of open issues here. This is the definition of a dead project. Please correct me if any development is happening because I cannot see any.
