### ISSUE TITLE
Unable to parse selectors with numeric values in exponential notation

### ISSUE THREAD

**Issue by aweary** [airbnb/enzyme#1155]
The parser will fail if you try to do `[val=2e8]` because it doesn't recognize `e` as a valid character for numeric constants. I'll work on a fix for rst-selector-parser

**Comment by masataka-kurihara** [comment]
additionally...

const Test = () => (<div id="0">text</div>);
const test = mount(<Test/>);
test.find('#0');

this code tells me 'Failed to parse selector: #0'.

**Comment by ljharb** [comment]
@masataka-kurihara that's because "0" is an invalid ID. IDs can not start with numbers.

**Comment by masataka-kurihara** [comment]
Thx, @ljharb . Oh, I usually do with wrong way but this can run under v2.

**Comment by ljharb** [comment]
Then that's a bug in v2 that v3 fixes :-)

**Comment by masataka-kurihara** [comment]
Sounds good. 

If you can, I want to tell me by the message how I am wrong.

**Comment by ljharb** [comment]
That's a much harder problem (for a parser to know why your unpsrseable thing is wrong) - I don't think that's going to be practical here.

**Comment by masataka-kurihara** [comment]
No problem, I think it for another one. I have understood. Thank you for your kindness.

**Comment by HansWurst90** [comment]
I encountered the same problem and found the reason here, thanks for explaining/pointing it out.
@ljharb 
But according to [HTML5 Recommendation](https://www.w3.org/TR/html5/dom.html#the-id-attribute):

> The `id` attribute specifies its element’s unique identifier (ID).
There are no other restrictions on what form an ID can take; in particular, IDs can consist of just digits, start with a digit, start with an underscore, consist of just punctuation, etc.

**Comment by ljharb** [comment]
Thanks - I believe you're right, and that I was incorrect. I also think that this is now fixed :-)

Please file a new issue if not.
