### ISSUE TITLE
Add a `.toJSX()` method to ShallowWrapper?

### ISSUE THREAD

**Issue by themouette** [airbnb/enzyme#116]
When using shallow rendering, it is useful to to compare JSX string.

Do you think it can fit in enzyme?

I managed to do this in my tests using [react-element-to-jsx-string](https://github.com/algolia/react-element-to-jsx-string) and the following code:

``` jsx
import React from 'react';
import { expect } from 'chai';
import { shallow } from 'enzyme'; 
import reactElementToJSXString from 'react-element-to-jsx-string';

describe('test JSX output', () => {
  it('should be done', () => {
    const component = shallow(<MyComponent />);
    expect(component.single(reactElementToJSXString))
      .to.equal(
`<div className="custom-wrapper">
  <Header>
    <h1>
      My Page Title
    </h1>
  </Header>
</div>`);
  });
});
```

**Comment by ljharb** [comment]
If you're producing that entire jsx string, you're not shallow rendering, you're deep rendering. Have you considered `render`?

**Comment by themouette** [comment]
Sorry, I shouldn't have taken an example with dom elements.

Let's consider this instead:

``` javascript
import React from 'react';
import { expect } from 'chai';
import { shallow } from 'enzyme'; 
import reactElementToJSXString from 'react-element-to-jsx-string';

const MyComponent = () => {
  return (<Page type="custom">
    <Header>My Page Title</Header>
    <Body>
      My Page Content
    </Body>
  </Page>);
};


describe('test JSX output', () => {
  it('should be done', () => {
    const component = shallow(<MyComponent />);
    expect(component.single(reactElementToJSXString))
      .to.equal(
`<Page type="custom">
  <Header>
    My Page Title
  </Header>
  <Body>
    My Page Content
  </Body>
</Page>`);
  });
});
```

The output is a JSX string that can be compared with expected result.

**Comment by ljharb** [comment]
Right - it's the same question tho, whether it's DOM elements or not. "shallow" means "only render the top level" - if you want to compare the whole tree, you're deep rendering it.

**Comment by themouette** [comment]
Maybe I missed something, but from my understanding, using `render` I would process `Page`, `Header` and `Body` as well.

Shallow rendering only renders the top level component, so it does not care about how `Page` renders.

**Comment by ljharb** [comment]
ah, so you're saying that in this case, "My Page Title" is a child passed down from `Page` to `Header`, and thus it would appear in the shallow jsx?

I think this makes sense - but it feels like it's very brittle, because it's tightly coupled to the jsx structure. Separate tests, that check that `Header` and `Body` render, are much stronger because changing the JSX structure won't result in a broken test.

**Comment by lelandrichardson** [comment]
@themouette you should be able to accomplish what you're wanting by using `.contains()`:

```jsx
describe('test JSX output', () => {
  it('should be done', () => {
    const component = shallow(<MyComponent />);
    expect(component.contains(
<Page type="custom">
  <Header>
    My Page Title
  </Header>
  <Body>
    My Page Content
  </Body>
</Page>)).to.equal(true);
  });
});
```

Although this isn't technically the same, since `contains` would match a subtree as well.

Rather than having things be string-based, we COULD add a method like `.equals()` that worked like `.contains()` but had to match the entire tree...

**Comment by themouette** [comment]
Indeed, `.equals()` would be perfect.
