### ISSUE TITLE
support react's hydrate for enzyme-adapter-react-16

### ISSUE THREAD

**Issue by brucewpaul** [airbnb/enzyme#1316]
It would be great to support testing react's hydrate method as opposed to just the render method. This could maybe be done via an options argument?

cc @ljharb

**Comment by ljharb** [comment]
With an empty DOM node, won't `hydrate` and `render` be identical?

**Comment by brucewpaul** [comment]
Ya I think so, but this would be able to specifically test server side rendering of a component.

cc @goatslacker

**Comment by ljharb** [comment]
Certainly `mount` invokes `ReactDOM.render`; an adapter option could be used in the v16+ adapter to specify `ReactDOM.hydrate` be used.

I'm just not sure what the point would be - all we'd be doing is testing ReactDOM itself, since `hydrate` and `render` theoretically do the same thing on an empty container.

**Comment by goatslacker** [comment]
There's currently a warning when you try to `render()` SSR'd markup, so it would at the very least silence that warning.

**Comment by ljharb** [comment]
In that case, maybe it'd be better to always use `hydrate` in the React 16 adapter here?

**Comment by goatslacker** [comment]
We should have both, for non server rendered content I think you want to use `render`
