### ISSUE TITLE
Do I have to re-query the wrapper to get the results

### ISSUE THREAD

**Issue by dagda1** [airbnb/enzyme#1409]
In enzyme 3, I have had to change the following test:

```
  it('should format a number correctly', () => {
    const wrapper = wrap({ dateParts: { day: '1' } });

    const day = wrapper.find('input').findWhere(x => x.props().name === 'day');

    setInput(day, '1');

    expect(day.props().value).toBe('01');
  });
```

To:
```
  it('should format a number correctly', () => {
    const wrapper = wrap({ dateParts: { day: '1' } });

    const day = wrapper.find('input').findWhere(x => x.props().name === 'day');

    setInput(day, '1');

    wrapper.update(); // does not appear to do anything

    expect(wrapper.find('input').findWhere(x => x.props().name === 'day').props().value).toBe('01');
  });
```

The `day` var does not update like it used to and I am having to re-query the wrapper to get the updated elements value.

Is this expected behaviour?

**Comment by ljharb** [comment]
Yes, this is mentioned in the migration guide: https://github.com/airbnb/enzyme/blob/master/docs/guides/migration-from-2-to-3.md#element-referential-identity-is-no-longer-preserved

**Comment by aronwoost** [comment]
@ljharb Thanks for clearing that up.

I had the same issue as @dagda1 and a tough time to relate the [migration guide example](https://github.com/airbnb/enzyme/blob/master/docs/guides/migration-from-2-to-3.md#element-referential-identity-is-no-longer-preserved) to this case. Actually I still don't get how the `ICONS` example connects to this issue. Probably because the example is somewhat non-real-life.

To avoid confusion for the people coming after us it's maybe better to provide a more practical example like the one from @dagda1. 

Abstract:
```
component = wrapper.find('query');
component.simulate('something');

// in enzyme@3 you need to re-query. Why is this so?
component = wrapper.find('query');

expect(component);
```

**Comment by ljharb** [comment]
@lelandrichardson can weigh in on why it's an improvement.

A PR to make the docs better is always appreciated!

**Comment by dagda1** [comment]
TBH, I did not understand the ICONS example so I think it could be better.
