### ISSUE TITLE
Wrong DOM dimensions after call to mount

### ISSUE THREAD

**Issue by pronebird** [airbnb/enzyme#1434]
DOM dimensions are invalid after call to `mount()`:

```
const test = mount(
  <div style={{ height: 100, overflow: 'hidden' }}></div>
);
expect(test.getDOMNode().clientHeight).to.be.equal(100); // reports 0 != 100
```

Running the same in browser works:

```
<html>
<body>
  <div style="height: 100px; overflow: hidden"></div>
  <script>alert(document.querySelector('div').clientHeight);</script>
</body>
</html>
```

Adding timeout after mount doesn't help either. It seems that enzyme is broken. I use electron-mocha to run tests in native environment.

**Comment by ljharb** [comment]
It's not that enzyme is broken; `getDOMNode()` is returning you a DOM node. The issue is that the DOM node itself is reporting a height of zero, probably because it's not actually visible. `clientHeight` doesn't test the style, it tests the *actual height*.

This looks like a minimal test case - can you provide your actual code, so we can see what you're trying to test? Generally you shouldn't need the DOM node.

**Comment by michaelpapworth** [comment]
I'm having a similar issue myself where `clientHeight` returns `undefined` instead of the actual height of the DOMElement.  This code **works as expected in the browser**. 

**Component**
```
class MyWidget extends React.Component {
    constructor() {
        super();
        this.state = { contentHeight: 0 };
    }

    componentWillReceiveProps(nextProps) {
        this.setState(() => ({
            contentHeight: nextProps.open ? this.content.clientHeight : 0
        }));
    }

    render() {
        const { controlId, open, trigger, children } = this.props;
        return (
            <div>
                <button tabIndex="0" aria-controls={controlId}>
                    { cloneElement(trigger, { open }) }
                </button>
                <div
                    id={controlId}
                    ref={(element) => {
                        this.content = element;
                    }}
                    aria-hidden={open}
                    style={{ maxHeight: this.state.contentHeight }}
                >
                    { cloneElement(children, { open }) }
                </div>
            </div>
        );
    }
}

```
However, when mounting the component and simulating a prop change, the `clientHeight` of the child `div` reports `undefined`.

**Unit Test**
```
// Arrange
const wrapper = mount(
    <MyWidget trigger={<span>click me</span>} open={false}>
        <div style={{ height: 90, padding: 5 }}>Lorum Ipsum</div>
    </MyWidget>
);

// Act
wrapper.setProps({ open: true });

// Assert
expect(wrapper.children('div').prop('style')).to.have.property('maxHeight', 100);

// Result
AssertionError: expected { maxHeight: undefined } to have a property 'maxHeight' of 100, but got undefined
```
I'm not entirely convinced that enzyme is the cause of this since it feels like its related to the underlying tooling or even JSDOM, but I suspect you've far more experience than I with `react-dom/test-tools` and may be able to target an issue in the appropriate direction.  For additional context I was led here from https://github.com/facebook/react/issues/11855

**Comment by ljharb** [comment]
@michaelpapworth I agree that it's likely related to jsdom. Have you tried running enzyme in an actual browser to confirm?

**Comment by pronebird** [comment]
Do you use JSDOM in Enzyme? We had tons of problems with it before, so we switched to running the actual browser with electron-mocha.

My mocha test setup looks as following:

```
  let container: ?HTMLElement;

  function renderIntoDocument(instance: React.Element<AccordionProps>) {
    if(!container) {
      container = document.createElement('div');
      if(!document.documentElement) {
        throw new Error('document.documentElement cannot be null.');
      }
      document.documentElement.appendChild(container);
    }
    return ReactDOM.render(instance, container);
  }

  // unmount container and clean up DOM
  afterEach(() => {
    if(container) {
      ReactDOM.unmountComponentAtNode(container);
      container = null;
    }
  });
```

**Comment by ljharb** [comment]
Yes, we use jsdom with enzyme and it works fine. However, we don't test for things like `clientHeight`, because it's not the responsibility of component unit tests to ensure the browser, or React is working.

In other words, I'm suggesting that's not a good test.

**Comment by pronebird** [comment]
In my case I test that the visual component provides the proper visual presentation. The component itself uses `clientHeight` to find out the height of the underlying DOM. Given that `clientHeight` is `undefined` there is no way for it to set the proper presentation and there is no way to test it because even the internal state which I could use in test cases is incorrect either.

**Comment by ljharb** [comment]
enzyme isn’t an appropriate visual testing tool; I’d recommend something like happo for that (for visual diffs).

Separately, all you need to test there is that you rendered a div with a style height of 100; the clientHeight is guaranteed there because of how React and the DOM work - so all you’d need to do is assert on the style.

**Comment by pronebird** [comment]
@ljharb makes sense! Thank you! 🙏
