### ISSUE TITLE
Enzyme simulate wheel scroll does not work.

### ISSUE THREAD

**Issue by Artimal** [airbnb/enzyme#1473]
Hi,
I am not able to simulate mouse wheel scroll on my wrapper. Following examples doesn't work:
```
wrapper.find('div#app-wrap').simulate('scroll');
wrapper.find('div#app-wrap').simulate('scroll', { deltaY: 50 });
wrapper.find('div#app-wrap').simulate('wheel');
wrapper.find('div#app-wrap').simulate('wheel', { deltaY: 50 });
```
The problem is my event.preventDefault() is "not defined" and all the test fails:
```
scrollHandler(event) {
	event.preventDefault();
	this.props.scrollScrolling({delta: event.deltaY});
}
```
The spy is always not called. How can I turn it inito life?
Greetings,
Arthur

**Comment by ljharb** [comment]
1) avoid `.simulate` entirely; it's best to invoke your prop function directly.
2) can you provide your full test code?

**Comment by ljharb** [comment]
@Artimal here's my list of tips to improve your tests:
1. Try to avoid passing strings into `.find` - in the case of Sidebar/Scrollbar/Route/ConnectedRouter, try passing the actual component constructor itself (iow, import it into your tests)
1. Instead of `.simulate('onWhatever', ...args)`, try `.prop('onWhatever')(...args)`
1. avoid snapshot testing; it's brittle.

Otherwise everything looks great!

Are you still having trouble, or can the issue be closed?

**Comment by Artimal** [comment]
@ljharb 
1. I just need to ask 'why?' to understand it :) Is that just better practise or it gives some exact profits?
2. Isn't that obvious that if you call .prop('onWhatever')(...args) it will always work? I tought that .simulate is more 'natural' and will actually simulate events like on working application.
3. Why again?! All that people from presentations of Jest snapshiting were wrong? Please explain or link me some sources! :)

**Comment by ljharb** [comment]
1. It’s a better practice because doing anything with strings is fuzzy. In this case, you aren’t trying to assert that it renders a component *named* Sidebar, you’re trying to assert that it’s rendering *an actual Sidebar* - finding with the constructor ensures that.
1. That’s exactly it - .simulate does not simulate anything whatsoever, it just looks up a prop value and invokes it. Better to be explicit and avoid the confusion.
1. When snapshots have a diff, what typically happens is that people just update the expected snapshot, and thus lose all the benefit of having a snapshot. The only time snapshots are useful is when you’re making zero-impact refactors and you want to ensure that you’ve had zero impact. If you’re making a meaningful change, there’s no point in having the snapshot anyways. Write explicit tests instead.

**Comment by Artimal** [comment]
@ljharb I understand it but is that even possible not to pass that test? In my imagination if I pass a spy as a prop to enzyme element and then I call that prop and expect called spy - it is imbosible to not pass it... So that test is useless?

**Comment by ljharb** [comment]
It’s quite possible. There’s no guarantee the component is sticking the function you provided onto the element it’s rendering.
