### ISSUE TITLE
Debug masks arrays and object contents

### ISSUE THREAD

**Issue by blainekasten** [airbnb/enzyme#1476]
[Repl for example](https://repl.it/repls/MediumInexperiencedAfricanrockpython)

This was just raised as an issue in [enzyme-matchers](https://github.com/blainekasten/enzyme-matchers/issues/186).

I expected debug to print everything. Should it? If not, any advice on a different way to implement a strict matching element?

**Comment by ljharb** [comment]
In https://github.com/airbnb/enzyme/commit/4f4c233096b944fef1c847a0ba38879d27556656, i improved the output for boxed primitives, but did not change the behavior for non-function objects.

I think that would be reasonable, and it'd be pretty trivial to change the `debug` output. @lelandrichardson, any idea why it was this way in the first place?

One possibility is that it could be done via an option to debug, so that the default output is minimal but the more verbose output is achievable.

**Comment by ljharb** [comment]
Fixed in #1547.
