### ISSUE TITLE
Error: Failed to parse selector: .layout-2/24

### ISSUE THREAD

**Issue by AbdullahAli** [airbnb/enzyme#1580]
I am trying to find a component with class `.layout-2/24` but I get an error:

```
Error: Failed to parse selector: .layout-2/24
```

The error seems to revolve around the `\`

Escaping it does not seem to fix the issue either, eg: `.layout-2\/24`

Any idea how to fix this please?

**Comment by ljharb** [comment]
Is that actually a valid class name?

**Comment by AbdullahAli** [comment]
I believe so, yes

Currently, it does not allow for a `/` anywhere within the class name

**Comment by ReactiveRaven** [comment]
`/` is not a valid character in a CSS class name.

The grammar is shown here: https://www.w3.org/TR/CSS22/grammar.html#scanner

The grammar says a css class is:

* a dot
* followed by `IDENT`

An `IDENT` is:

* One to many of:
  * `a-z`, or 
  * `A-Z`, or 
  * `0-9`, or 
  * `_`, or 
  * `-`, or 
  * a unicode escape sequence (eg `\FF`), or 
  * any non-hex character that is escaped (eg `\x`), or 
  * any character above octal `240` ([`0xA0` in hex](https://en.wikipedia.org/wiki/Latin-1_Supplement_(Unicode_block)#Character_table))
* But the first character must not be `0-9`

And so:

`/` is not one of the explicitly allowed characters, and has the hex value `0x2F` - `0x2F` is less than `0xA0`. So is not allowed, according to the spec.

That said, escaping it as `.layout-2\/24` _would be allowed_ by the grammar. But that would need to be on both sides (as the class in rendered output, and in the selector passed to `.find()`) - enzyme expects the classes to match naïvely, so it would not return the element/component with one side escaped and the other unescaped, because as far as it is concerned, `foo` and `f\oo` are different.

But. [The code that throws the underlying error](https://github.com/airbnb/enzyme/blob/4d4f7bd72886d9665394db72506cef5eeda32494/packages/enzyme/src/selectors.js#L60) is in `rst-selector-parser` (which was created for enzyme). The [regex in rst-selector-parser does not handle escapes](https://github.com/aweary/rst-selector-parser/blob/master/src/grammar.ne#L78) at all. So that is the place that needs updating to handle escaped characters, if the Enzyme team decides to support this use case.

**Comment by ljharb** [comment]
In that case, an issue should be filed there, and this can be closed. Thanks for the legwork!
