### ISSUE TITLE
React.Children.only - difference between shallow and mount

### ISSUE THREAD

**Issue by mir3z** [airbnb/enzyme#1635]
Consider the following code snippets:

```js
const Parent = ({ children }) => <div>{ React.Children.only(children) }</div>;
const Child = () => <span>child</span>;

mount(<Parent><Child /></Parent>).debug() // [1]
shallow(<Parent><Child /></Parent>).debug() // [2]
```

### Current behavior
Executing [1] produces

```jsx
<Parent>
  <div>
    <Child>
      <span>
        child
      </span>
    </Child>
  </div>
</Parent>
```

but executing [2] gives:

```jsx
<div>
  <Child />
</div>
```

### Expected behavior
The problem here is that in [1] I have `<Parent />` whereas it's missing in [2].

I'm not sure which one is expected... But I think [1] is more desired as I'd like to have a way to verify that `<Parent />` is there even though it renders only its children.

### Your environment
macOS Sierra

#### API

- [X] shallow
- [X] mount
- [ ] render

#### Version

| library         | version
| ---------------- | -------
| Enzyme           |  3.2.0
| React            |  16.2.0

#### Adapter

- [X] enzyme-adapter-react-16
- [ ] enzyme-adapter-react-15
- [ ] enzyme-adapter-react-15.4
- [ ] enzyme-adapter-react-14
- [ ] enzyme-adapter-react-13
- [ ] enzyme-adapter-react-helper
- [ ] others ( )

**Comment by mykhailo-riabokon** [comment]
@mir3z `shallow` and `mount` suppose to work differently. [.mount()](https://github.com/airbnb/enzyme/blob/master/docs/api/mount.md) equals to `Full DOM rendering` and when you `debug` it you see whole tree.  [.shallow()](https://github.com/airbnb/enzyme/blob/master/docs/api/shallow.md)  rendering lets you render a component [“one level deep”](https://reactjs.org/docs/test-utils.html#shallow-rendering), so even if you you child looks like:
```javascript
const Child = () => <span>child <OneMoreComponent /></span>
```
debug output still will be 
```
<div>
 <Child />
</div>
```

[React.Children.only](https://reactjs.org/docs/react-api.html#reactchildrenonly) is not connected to `shallow` or `mount` it's a helper which will throw an error if child is not React element, like:
```
shallow(<Parent><Child /><Child /></Parent>).debug() // throw an error
shallow(<Parent>{() => <Child />}</Parent>).debug() // throw an error
```

And now your test case, could you describe it a bit more? Because when you are rendering a `Parent` why do you need to test that `Parent` is in output as you just rendered it?

**Comment by ljharb** [comment]
This is indeed because shallow and mount work differently - shallow is what is being *rendered* by the component, mount is the component itself.

**Comment by ljharb** [comment]
This seems answered.
