### ISSUE TITLE
3.4.1 breaks existing tests/API

### ISSUE THREAD

**Issue by hbowden** [airbnb/enzyme#1747]
**Describe the bug**
When running our test suite with the latest version of enzyme we get: 
![2018-08-09 15_14_34-hyper](https://user-images.githubusercontent.com/12447474/43923291-f425b5aa-9be6-11e8-92da-9d1ec0969808.png) 

When we run tests with enzyme 3.3.0 all the tests pass. When we run with 3.4.1 most of our tests break with the error message above.

**To Reproduce**
1. git clone https://github.com/DigitalRiver/react-atlas
2. npm install
3. npm install enzyme@3.4.1
4. npm run test

**Expected behavior**
Tests pass and don't return error in screenshot above.

**Desktop (please complete the following information):**
 - OS: [Windows 7]
 - Browser [FF 61.0.1]

**Comment by hbowden** [comment]
@ljharb If enzyme tests passed before with out strings it should continue to work without strings otherwise your breaking a public API. It doesn't matter if it was a "bug fix" or not updating minor versions shouldn't break existing tests. And if you are going to be making breaking changes to enzyme it needs to be in a new major version release, not a minor version release.

**Comment by hbowden** [comment]
Tests pass with strings on 3.4.1 and they passed before on 3.3.0 with components so it seems like enzyme 3.3.0 allowed for both and 3.4.1 only allows for strings, which is a Public API breakage in a minor release.  Shouldn't there be a deprecation warning so users know about this?

**Comment by ljharb** [comment]
Every bug fix is a "breaking change" if you're relying on the bug; we'd never be able to ship bugfixes as a patch version if the criteria was as simple as "every passing test must remain passing".

Again, that the tests passed for you doesn't indicate that they were actually testing what you think they were.

The exception you're receiving is the deprecation warning. I suppose I could convert the exception to a `console.warn`, but hopefully most enzyme users have console warnings/errors set to fail tests anyways, so that propType warnings fail tests.

If you convert them from elements to component constructors (not strings), do your tests pass in both v3.3 and v3.4?

**Comment by ljharb** [comment]
I'm going to close this, on the assumption that the fact that these tests passed previously was a bug, which is now fixed.

Happy to reopen it if this is incorrect.
