### ISSUE TITLE
enzyme-adapter-react-16 Can't resolve 'enzyme/build/Utils'

### ISSUE THREAD

**Issue by makethisbuildthat** [airbnb/enzyme#1750]
**Describe the bug**
In enzyme-adapter-react-16 ReactSixteenAdapter.js, it is requiring 'enzyme/build/Utils', but it doesn't exist.

**Comment by ljharb** [comment]
It certainly exists: https://unpkg.com/enzyme@3.4.1/build/Utils.js

What version of enzyme are you using? Be sure to run `npm ls`; if that exits nonzero, then your dep graph is invalid, and you can't expect anything to work.

**Comment by mvargeson** [comment]
@makethisbuildthat I ran into this same error although my fix may not work for you if we don't have the same root cause.

I started by searching through `yarn list` based on @ljharb's comment to find if there were any obvious issues there but there weren't.

In the end, it turned out that a [webpack](https://github.com/webpack/webpack) alias was the cause. I don't know what changed recently but it definitely ended up causing problems. Removing the alias fixed the error.

**Comment by ljharb** [comment]
I’m confused why a webpack alias would apply to node tests, but glad you figured it out!

**Comment by mvargeson** [comment]
I should have put some more context around this. We have a package that runs tests with [testem](https://github.com/testem/testem) and [mocha](https://github.com/mochajs/mocha) and requires the package to build with tests before running which is why [webpack](https://github.com/webpack/webpack) was involved for us in this case.

This was a non-issue in our packages that use [jest](https://github.com/facebook/jest).
