### ISSUE TITLE
Problem running with jest

### ISSUE THREAD

**Issue by mauriciosoares** [airbnb/enzyme#179]
Hey guys, I'm doing some tests with enzyme in my Jest environment, and I got a problem when I ran the test command...

```
TypeError: <path>/src/shared/components/fieldset/__tests__/fields.js:
<path>/node_modules/enzyme/build/index.js:
<path>/node_modules/enzyme/build/ReactWrapper.js:
<path>/node_modules/enzyme/build/Debug.js:
<path>/node_modules/object.values/index.js:
<path>/node_modules/object.values/implementation.js:
<path>/node_modules/es-abstract/es7.js:
<path>/node_modules/es-abstract/es6.js: Cannot convert undefined or null to object
```

I believe this is cause jest is mocking the `object.values` and `es-abstract` modules, after I put them in the `unmockedModulePathPatterns` array it started working flawlessly.

Should these be put in the [docs](http://airbnb.io/enzyme/docs/guides/jest.html) as well?

Cheers.

**Comment by lelandrichardson** [comment]
@mauriciosoares yes, please!

**Comment by blainekasten** [comment]
It should also be noted this is a bug due to npm3. Users of npm2 won't face this issue. It's only due to jest not knowing how to mock the flat tree structure right now. This will go away when their haste2 implementation gets merged. at that point it will only need the `enzyme` module to be put in there.

**Comment by mauriciosoares** [comment]
I've created a PR that adds these modules in the docs.

nice to know @blainekasten, I'll follow this up.
