### ISSUE TITLE
shallow find component sometimes doesn't find a rendered component

### ISSUE THREAD

**Issue by timothyjlaurent** [airbnb/enzyme#182]
I am rendering a component with 
```
      const wrapper = shallow(<GeneCentricView  {...this.props} />)
```
Then checking for the existence of child components:
```
      [GeneDetailsSection, MolecularConditionInformationSection, InternalNotesSection].forEach((component) => {
         expect(wrapper.find(component).length).toBe(1);
      })
```
The first 2 expects `GeneDetailsSection` and`MolecularConditionInformationSection` work but the third has a length of 0.

Debugging the wrapper shows it has been renedered:

```
> wrapper.debug()
"<div>
<div className="network-builder">
Network Builder
</div>
<GeneDetailsSection geneId={1} gene={{...}} />
<MolecularConditionInformationSection geneId={1} gene={{...}} />
<InternalNotesSection geneId={1} gene={{...}} />
</div>"
```

What is going on here? Is there a better way to test for child components?

**Comment by lelandrichardson** [comment]
@timothyjlaurent this seems strange. The most likely culprit is that you for some reason have two different versinos of the `InternalNotesSection` constructor. Is there some tool you are using that might be invalidating your require cache and causing node to parse the `InternalNotesSection` file again?

We have seen this behavior internally at Airbnb when people use tools like proxyquire, rerequire, etc.

One thing that you can do is pass in the component name instead of the actual constructor:

```
wrapper.find('InternalNotesSection')
```

I prefer passing the constructor in as it ensures referential equality, but there may be something about your environment that is causing more than one to be created.

**Comment by timothyjlaurent** [comment]
AFAIK there is no special tooling aside from Webpack, no proxyquire or rerequire. I'll stick to the component name for now, I guess.

**Comment by timothyjlaurent** [comment]
So 1 last question, to be able to use the component name do I really need to assign a `displayName` property to the component? Or will it work without that?

**Comment by lelandrichardson** [comment]
it will work if you're using `class MyComponent extends React.Component { ... }` syntax, or if you're using a named function expression.

**Comment by timothyjlaurent** [comment]
Great - I'll keep that in mind for any lingering `React.CreateClass({})` components. I'll close this -- It's still strange that using the function selectors doesn't work.

**Comment by lelandrichardson** [comment]
@timothyjlaurent AFAIK it works for `React.createClass` as well.

**Comment by dougajmcdonald** [comment]
We found a similar issue where the casing of the import statements were inconsistent between the test and application files.
We were also using webpack and alias' so we assumed it was webpack trying to be helpful and transpile files found in a case insensitive search but generating two different outputs.

**Comment by ljharb** [comment]
Using eslint-plugin-import can catch that.
