### ISSUE TITLE
FormData and missing value/defaultValue causes error in mount

### ISSUE THREAD

**Issue by thekevinscott** [airbnb/enzyme#1871]
[Here is a Github repo demonstrating the issue.](https://github.com/thekevinscott/test-form-data)

(I recognize this is a fairly narrow use case, but it does seem like a bug thus I felt it prudent to report it.)

### Current behavior
1. `mount` on a component with an `<input />` missing a `value` or `defaultValue` prop
2. In that component, attach a `ref` to the surrounding `<form />` element
3. Test a method, `handleSubmit`, that constructs a `FormData` object initialized with the form's `ref`
4. Observe the error "TypeError: Cannot read property 'replace' of null"

### Expected behavior
Receive a FormData object regardless of whether value is set or not. The browser handles this case fine. Setting an explicit `value` or `defaultValue` works fine.

### Your environment
Node: v10.12.0
Browser: Latest Chrome

#### API

- [ ] shallow
- [x] mount
- [ ] render

#### Version

| library             | version
| ------------------- | -------
| enzyme              |  3.7.0
| react               |  16.5.2
| react-dom           |  16.5.2
| react-test-renderer | N/A
| adapter (below)     | 

#### Adapter

- [x] enzyme-adapter-react-16
- [ ] enzyme-adapter-react-16.3
- [ ] enzyme-adapter-react-16.2
- [ ] enzyme-adapter-react-16.1
- [ ] enzyme-adapter-react-15
- [ ] enzyme-adapter-react-15.4
- [ ] enzyme-adapter-react-14
- [ ] enzyme-adapter-react-13
- [ ] enzyme-adapter-react-helper
- [ ] others ( )

**Comment by EdwinGuzman** [comment]
Did you ever solve this issue or find a way to test form submission with FormData and refs?

**Comment by ljharb** [comment]
This seems like a jsdom bug. The ref - whether you use createRef, or a ref callback - is an HTMLFormElement in `mount`.

However, when I dig into the jsdom code - specifically, `node_modules/jest-environment-jsdom/node_modules/jsdom/lib/jsdom/living/xhr/FormData-impl.js` line, it's passing `entry.value` as `null`  into `normalizeToCRLF`.

In other words, this isn't an issue with enzyme, it's with jsdom, and you'll need to file it there.

Thanks very much for the repro, and I'm happy to reopen this if it turns out there's something enzyme can do to help.
