### ISSUE TITLE
unmount regression in 3.4.0

### ISSUE THREAD

**Issue by ZebraFlesh** [airbnb/enzyme#1880]
### Current behavior
Using enzyme 3.3.0, it is possible to do the following:
```
const wrapper = mount(<MyComponent />);
expect(wrapper.find('.my-component')).to.exist;
wrapper.unmount();
expect(wrapper.find('.my-component')).to.not.exist;
```
When upgrading to 3.4.0, the last line now fails with `Error: Method “name” is only meant to be run on a single node. 0 found instead.` Indeed, adding `console.log(wrapper.name())` after the unmount call results in the same error.

### Expected behavior
Unmounted wrapper continues to function as expected in 3.3.0

#### API

- [ ] shallow
- [X] mount
- [ ] render

#### Version

| library             | version
| ------------------- | -------
| enzyme              | 3.4.0 (also applies to 3.7.0) 
| react               | 16.4.1
| react-dom           | 16.4.1
| react-test-renderer | 16.2.0
| adapter (below)     | 1.6.0

#### Adapter

- [X] enzyme-adapter-react-16
- [ ] enzyme-adapter-react-16.3
- [ ] enzyme-adapter-react-16.2
- [ ] enzyme-adapter-react-16.1
- [ ] enzyme-adapter-react-15
- [ ] enzyme-adapter-react-15.4
- [ ] enzyme-adapter-react-14
- [ ] enzyme-adapter-react-13
- [ ] enzyme-adapter-react-helper
- [ ] others ( )

**Comment by ljharb** [comment]
I'm a little confused; what calls `.name()`? It might be your `to.exist` matcher; what happens if you use something more explicit?

**Comment by ZebraFlesh** [comment]
I'm using chai-enzyme for that. Digging into that code, it seems like that may be the source of the issue: chai-enzyme is checking that the enzyme `wrapper.length > 0`, failing, and then trying to report it (likely using the name). However, this a change that I noticed during debugging:
- v3.3.0: mounted enzyme wrapper has length 1 after unmount
- v3.4.0: mounted enzyme wrapper has length 0 after unmount

So is that an enzyme regression, an intended change, and/or an implementation detail which chai-enzyme should perhaps not be leveraging?

**Comment by ljharb** [comment]
It looks like the change was made in #1498 - specifically, [this line](https://github.com/airbnb/enzyme/pull/1498/files#diff-f51a48d4631e74e85755869409584c3fL85) was removed, which (imo incorrectly) forced the length to be `1`.

In other words, I think it's an intentional bug fix - and as far as chai-enzyme goes, i think they were unintentionally relying on the erroneous behavior to have `.name()` work.

Could you rewrite your test case to use `.name()` and not chai-enzyme, with what happens in 3.3 vs 3.4? We may still be able to fix that particular method, which would unbreak your chai-enzyme use case.

**Comment by ljharb** [comment]
@ZebraFlesh closing; happy to reopen if you can make the change in my previous comment and there's something we can fix.
