### ISSUE TITLE
Enzyme displayName selector doc outdated

### ISSUE THREAD

**Issue by jimmywongroo** [airbnb/enzyme#1926]
### Current behavior

> NOTE: This will only work if the selector (and thus the component’s displayName) is a string starting with a capital letter. Strings starting with lower case letters will assume it is a CSS selector using the tag syntax.

https://airbnb.io/enzyme/docs/api/selector.html#4-a-react-components-displayname

Selecting an HOC wrapped component with displayName `withHOC(MyComponent)` seems to work, the doc is inaccurate.

### Expected behavior

Verify/clarify the note or remove it.

**Comment by ljharb** [comment]
Sounds like we should update the docs, thanks!

**Comment by ljharb** [comment]
@k3ithl1m anything with the help wanted label is especially welcome to make a PR for :-)

**Comment by k3ithl1m** [comment]
@ljharb I'm trying to work on the documentation. And I was trying to run a test to see if it really works. But maybe its because I'm still not familiar with enzyme and i've never used this function before but I'm not able to duplicate the behavior above nor was I able to even duplicate the behavior in the current document. I wanted to focus on working on the other feature first and maybe come back to this later, or potentially just write a documentation based on the OP's comment.

if i were to work on the later one. (Update documentation based on the OP's comment)
should I update the documentation to something like 
`enzyme allows you to find components based on a component’s displayName. If a component exists in a render tree where its displayName is set and has its first character as a capital letter, a string can be used to find it:

function MyComponent() {
  return <div />;
}
MyComponent.displayName = 'My Component';

// find instances of MyComponent
const myComponents = wrapper.find('My Component');
NOTE: This will only work if the selector (and thus the component’s displayName) is a string starting with a capital letter. Strings starting with lower case letters will assume it is a CSS selector using the tag syntax. However, selecting a HOC wrapped component even with lowercase letters (for example, withHOC(MyComponent)) will work.`

**Comment by ljharb** [comment]
Something like that seems reasonable; let's iterate on it in the PR.
