### ISSUE TITLE
Is not .to.have.lengthOf a api of jest???

### ISSUE THREAD

**Issue by 951565664** [airbnb/enzyme#1974]
### Your environment
window

#### Version

| library             | version
| ------------------- | -------
| enzyme              | "3.6.0"

#### Adapter

- [x] enzyme-adapter-react-16

-------------------------------
I followed the documentation and an error occurred.

In document
https://github.com/airbnb/enzyme/blob/3fb45940f44ef73fcd6bb370103af5f4101d2051/docs/api/ReactWrapper/detach.md
```js
// create a div in the document to mount into
const div = global.document.createElement('div');
global.document.body.appendChild(div);

// div is empty. body has the div attached.
expect(document.body.childNodes).to.have.lengthOf(1);
expect(div.childNodes).to.have.lengthOf(0);
```
error:
![image](https://user-images.githubusercontent.com/22285404/50944766-b2f81f00-14cc-11e9-9839-c60352e21cb0.png)

my code
```js
describe('document', () => {
  it('should render correct', () => {
    const div = global.document.createElement('div')
    global.document.body.appendChild(div)
    expect(document.body.childNodes).to.have.lengthOf(1)
    expect(div.childNodes).to.have.lengthOf(0)
  })
})
```

Is not `.to.have.lengthOf` a api of jest???

**Comment by 951565664** [comment]
I find `.to.have.lengthOf` is a api of chain https://www.chaijs.com/api/bdd/

**Comment by ljharb** [comment]
Yes, we use chai's `expect` exclusively.

**Comment by ElagrebiAli** [comment]
Jest can be used without Enzyme to render components and test with snapshots, Enzyme simply adds additional functionality.
Enzyme can be used without Jest, however Enzyme must be paired with another test runner if Jest is not used (in the documentation they use chai as the test runner as i know)
so in react , when you using create-react-app in your react Application ,it use Jest as unit testing runner in its configuration .. so you must use : 
Jest as the test runner, assertion library, and mocking library
Enzyme to provide additional testing utilities to interact with elements
so in your case you do this : 

`describe('document', () => {
  it('should render correct', () => {
    const div = global.document.createElement('div')
    global.document.body.appendChild(div)
    const wrapper=shallow( global.document.body)
    expect(wrapper.length).toBe(1)
    expect(wrapper.find('div').shallow.length).toBe(0)
  })
})`

and you can optimize it with your needs , but i recommand you to use shallow and read this article 
[https://medium.com/codeclan/testing-react-with-jest-and-enzyme-20505fec4675](url)
if i'm wrong please reply to me , because i'm currently try to learn and use enzyme and that is what i found.
thank u

**Comment by ljharb** [comment]
@ElagrebiAli `chai` is an assertion library; by using it, we can use `jest` or `mocha` interchangeably on all of our tests and examples.

**Comment by ElagrebiAli** [comment]
first of all ,thank you for ur respond .
yeah , you are right , i was wrong when i see "hey use chai as the test runner"
but what i mean exactly ,when can use only the expectation of jest , we don't need to configure or install chai .. as i know jest do its best  for assertion .
and thank you for ur patience .

**Comment by ljharb** [comment]
Right - we use chai explicitly so that we aren't locked in to jest, and can switch at any time.

**Comment by ElagrebiAli** [comment]
Great .i got it now .
thank you for your understanding @ljharb

**Comment by JoshuaVSherman** [comment]
might be  helpful to add not in documentation that the example is using 'chai assertions, not jest', most people will be using jest so it causes confusion

**Comment by ljharb** [comment]
“most people will be using jest” is both untrue and impossible to prove; it would cause confusion either way.
