### ISSUE TITLE
Unknown plugin "transform-replace-object-assign" specified in "/node_modules/airbnb-prop-types/.babelrc" attempted to resolve relative to "/node_modules/airbnb-prop-types"

### ISSUE THREAD

**Issue by salmankhann** [airbnb/enzyme#2240]
Thanks for reporting an issue to us! We're glad you are using and invested in Enzyme.
Before submitting, please read over our commonly reported issues to prevent duplicates!

### Current behavior
jest is failing to compile because of an issue with react-adapter-16, specifically, the package airbnb-prop-types that includes .babelrc. Babel tries to compile airbnb-prop-types and does not find presets and plugins. I am ignoring all node_modules from transformation except only specific libraries as follows:
```
"transformIgnorePatterns": [
      "<rootDir>/node_modules/(^generic-)/i",
      "<rootDir>/node_modules/react-infinite-scroller"
    ],
```

If I dig into node_modules and delete .babelrc from airbnb-prop-types, the build works just fine, but CI fails.

What am I doing wrong? Also, is there a specific reason that enzyme publishes .babelrc to npm because no other lib that I am using does so.

### Expected behavior
Unknown plugin "transform-replace-object-assign" specified in "/node_modules/airbnb-prop-types/.babelrc" attempted to resolve relative to "/node_modules/airbnb-prop-types"
#### API

- [ ] shallow
- [ ] mount
- [ ] render

#### Version

| library             | version
| ------------------- | -------
| enzyme              | 3.4.0
| react               | 16.9.0
| react-dom           | 16.9.0
| react-test-renderer | -
| adapter (below)     | 

#### Adapter

- [x] enzyme-adapter-react-16
- [ ] enzyme-adapter-react-16.3
- [ ] enzyme-adapter-react-16.2
- [ ] enzyme-adapter-react-16.1
- [ ] enzyme-adapter-react-15
- [ ] enzyme-adapter-react-15.4
- [ ] enzyme-adapter-react-14
- [ ] enzyme-adapter-react-13
- [ ] enzyme-adapter-react-helper
- [ ] others ( )

**Comment by ljharb** [comment]
Looks like you’re trying to transpile node_modules, which is a very dangerous thing to do - you wouldn’t get this error if you weren’t trying to transpile airbnb-prop-types (which is a different repo).

Including a .babelrc is common outside the RN ecosystem, but it rarely comes up because node_modules is ignored by babel by default.

I think your first pattern may not be doing what you think it’s doing - patterns aren’t regexes.

Closing; if you’re still having trouble, please file an issue on babel itself.
