### ISSUE TITLE
Add nested CSS Selector support

### ISSUE THREAD

**Issue by lelandrichardson** [airbnb/enzyme#23]
For example:

```
wrapper.find('.foo .bar')
```

**Comment by badeball** [comment]
Hi, @lelandrichardson 

I've actually been thinking for a while about creating a CSS selector engine for the virtual DOM of React. Particularly because I recently released a DOM-agnostic XPath [implementation](https://github.com/badeball/xpath-react) that also works on it (which I've personally have found to be very useful for the purpose of testing). Perhaps this can be of use to you?

**Comment by blainekasten** [comment]
Closing issue as PR has been merged! 🎉
