### ISSUE TITLE
Contains versus find

### ISSUE THREAD

**Issue by Andarist** [airbnb/enzyme#258]
Is there any reason why their implementations differ so much?

I have a big issue with contains implementation as:

1. It returns false positives when shallow rendered functional component contains text node, their types (both undefined) match and therefore they return in the end of nodeEqual true incorrectly. I might send a PR with a fix when I find some time to write tests for it, so stay tuned. EDIT:// Well, I've found eventually that there is assumption there React elements are passed in and not selectors, but anyway I'll submit my PR so maybe some future developer wont stumble upon this issue

2. Contains return false in 90% of my use cases. I need to add that I use functional components al over the place, I couldn't identify exact logic WHY does it matter yet, but I've found a workaround of this issue in using find instead of contains and just checking length of the outcome. After that I've looked into find implementation as well and I realised that find builds a predicate based on the input selector and it recognises functional components just fine.

Shouldn't find and contains be stream lined to share most of the logic?

**Comment by lelandrichardson** [comment]
@Andarist `.contains(x)`should really be thought of as `.contains(subtree)`.  It uses our `nodeEqual` hueristic to match entire trees (ie, nodes + children).  This ends up only really being practical for finding "leaf-node" components or almost-leaf-node components.

`.find(selector)` on the other hand uses our `selector` hueristic which is a more flexible way of finding things (and akin to CSS selectors in the case of a string selector).

Can you show us a case where `.contains()` fails where you think it shouldn't?  We've been getting a fair amount of bugs related to SFCs so it's possible that you are getting false because of a bug.

**Comment by Andarist** [comment]
https://github.com/airbnb/enzyme/pull/259 ;)

**Comment by Aweary** [comment]
@Andarist is there anything else actionable here?

**Comment by Andarist** [comment]
Not rly ;)
