### ISSUE TITLE
@import! - unit testing issue

### ISSUE THREAD

**Issue by lovelydreamer** [airbnb/enzyme#369]
Hello, 
I've found a bug with Enzyme. It tries to parse the following import statements and causes an error:

```
import 'script!jquery';
import 'script!what-input';
import 'script!foundation-sites';
```

Below is a link to the Stack Overflow issue for more details. 

https://stackoverflow.com/questions/37040291/unit-testing-in-react-mocha-enzyme-i-webpack-how-to-ignore-imported-file

**Comment by ljharb** [comment]
@lovelydreamer enzyme doesn't parse import statements - I'm not familiar with that particular import syntax, but it seems like something you'd need to configure your webpack setup to handle.

Please update here if you figure it out, since even though it's unrelated to enzyme, other enzyme users may benefit from your solution :-)
