### ISSUE TITLE
Native dom validation methods like checkValidity are not available

### ISSUE THREAD

**Issue by Yuripetusko** [airbnb/enzyme#374]
I am testing a component that renders and input field with onChange function that does `event.target.checkValidity()`. Now If I simulate change event with enzyme, I get `TypeError: event.currentTarget.checkValidity is not a function`. Is there any way around it? Maybe some advice on how to mock `checkValidity` ?

Thanks

**Comment by Aweary** [comment]
If you're using `mount` you should be getting an instance of `SyntheticEvent`. You can access the native event at `event.nativeEvent`

**Comment by Yuripetusko** [comment]
Thanks @Aweary for a quick response. 

So I tried `event.nativeEvent.currentTarget.checkValidity()` in my component but got `Cannot read property 'checkValidity' of undefined`

**Comment by Yuripetusko** [comment]
I think I will get better results by mocking `onChange` somehow to write my own implementation of DOM `checkValidity`

**Comment by Aweary** [comment]
So `event.currentTarget` should return the current target, but if you're using `mount` then you're using `jsdom` which doesn't currently support `checkValidity` which is the main problem here.

**Comment by Yuripetusko** [comment]
Ah ok that makes more sense. I'll visit `jsdom ` github page to see if this is in a roadmap. Meanwhile will try to work around it somehow. Thanks. I will close this issue now.

**Comment by Yuripetusko** [comment]
Just for reference: https://github.com/tmpvar/jsdom/issues/544

**Comment by hjylewis** [comment]
Would it be possible to add https://github.com/hyperform/hyperform to the jsdom setup like tmpvar/jsdom#544 suggests?

**Comment by papadi** [comment]
So, there is no workaround for this?

**Comment by EricHenry** [comment]
For anyone having issues when testing React components using Jest and Enzyme I was able to polyfill JSDOM by using the [hyperform package.](https://github.com/hyperform/hyperform/)

In your test file you can do the following after installing hyperform.
```js
import * as hyperform from 'hyperform';

var global = global;

const defineValidity = {
  get() {
    return hyperform.ValidityState(this);
  },
  configurable: true
};

global.HTMLFormElement.prototype.checkValidity = function() {
  return hyperform.checkValidity(this);
};

Object.defineProperty(global.HTMLFormElement.prototype, 'validity', defineValidity);
Object.defineProperty(global.HTMLInputElement.prototype, 'validity', defineValidity);
Object.defineProperty(global.HTMLSelectElement.prototype, 'validity', defineValidity);
Object.defineProperty(global.HTMLTextAreaElement.prototype, 'validity', defineValidity);
```

you can follow the same method for any other HTMLElements you may need to modify or any other attributes you need to polyfill.

**Comment by hjylewis** [comment]
This was our solution also using hyperform:


```js
// Jest Config
{
    "testEnvironment": "./jestSuperJSDOMEnvironment.js"
}
```


```js
// jestSuperJSDOMEnvironment.js

const JSDOMEnvironment = require('jest-environment-jsdom-latest');

// Extends JSDOM to include polyfills
class SuperJSDOMEnvironment extends JSDOMEnvironment {
  constructor(config) {
    super(config);
    global.window = this.global;
    global.document = this.document;

    // Add Form Validation polyfill
    // `require` down here because package has side-effects that change `global.window`/`global.document`
    const hyperform = require('hyperform'); 
    hyperform(this.global);
  }
}

module.exports = SuperJSDOMEnvironment;
```

**Comment by Lezlee85** [comment]
The Jest docs suggests [mocking methods which are not implemented in JSDOM](https://jestjs.io/docs/en/manual-mocks#mocking-methods-which-are-not-implemented-in-jsdom). I think this is a cleaner solution than polluting your environment because of tests.

My solution was to mock the native implementation of `DOMTokenList`

```
window.DOMTokenList = jest.fn().mockImplementation(query => {
    let list = [];

    return {
        remove: jest.fn().mockImplementation((item) => {
            const idx = list.indexOf(item);

            if (idx > -1) {
                list.splice(idx, 1)
            }
        }),
        add: jest.fn().mockImplementation((item) => {
            list.push(item);
        }),
    };
});
```
Then I used that to pass data to the event handler

```
submitBtn.simulate('click', {
        currentTarget: {
            form: {
                checkValidity: () => false,
                classList: new DOMTokenList()
            }
        },
        preventDefault: jest.fn(),
        stopPropagation: jest.fn()
    })
```
Only problem I have with this is that nasty little closure in the mock implementation of `DOMTokenList`. I'll modify that if I figure out how to pass context to a mock implementation like this one.

FYI: I'm using Enzyme's `shallow` rendering for this, `mount` doesn't seem to work with this solution

**Comment by Lezlee85** [comment]
The Jest docs suggests [mocking methods which are not implemented in JSDOM](https://jestjs.io/docs/en/manual-mocks#mocking-methods-which-are-not-implemented-in-jsdom). I think this is a cleaner solution than polluting your environment because of tests.

In my specific case, I needed to validate a form and then inspect the `classList` of the form for the presence of a certain class, the presence of which would inform me about the form's validity.

My solution was to mock the form's properties e.g mock the native implementation of `DOMTokenList` for `classList` property inside 

```
beforeAll(() => {
    window.DOMTokenList = jest.fn().mockImplementation(() => {
        return {
            list: [],
            remove: jest.fn().mockImplementation(function (item) {
                const idx = this.list.indexOf(item);

                if (idx > -1) {
                    this.list.splice(idx, 1)
                }
            }),
            add: jest.fn().mockImplementation(function (item) {
                this.list.push(item);
            }),
            contains: jest.fn().mockImplementation(function (item) {
                return this.list.indexOf(item) > -1;
            })
        };
    });
})
```
Then I used that to pass properties to the event handler. I'm able to access the form in my react component from the submit button with `event.currentTarget.form`

```
let mockClassList = new DOMTokenList();

submitBtn.simulate('click', {
        currentTarget: {
            form: {
                checkValidity: () => false,
                classList: mockClassList
            }
        },
        preventDefault: jest.fn(),
        stopPropagation: jest.fn()
    })
```

This allows me to set the validity of the form to false and true, and inspect the `mockClassList` for the presence of the `was-validated` class each time

```
    submitBtn.simulate('click', {
        currentTarget: {
            form: {
                checkValidity: () => false,
                classList: mockClassList
            }
        },
        preventDefault: jest.fn(),
        stopPropagation: jest.fn()
    });

    expect(mockClassList.contains('was-validated')).toBeTruthy();

    submitBtn.simulate('click', {
        currentTarget: {
            form: {
                checkValidity: () => true,
                classList: mockClassList
            }
        },
        preventDefault: jest.fn(),
        stopPropagation: jest.fn()
    });

    expect(mockClassList.contains('was-validated')).toBeFalsy();
```


FYI: I'm using Enzyme's `shallow` rendering for this, `mount` doesn't seem to work with this solution

**Comment by IronSean** [comment]
I had success with @hjylewis's approach, with the one caveat that I had to change one line to `global.document = this.global.document;` using `jest-environment-jsdom: 23.4.0`.

**Comment by cuongluu8** [comment]
I took a slightly different approach to this problem.
I created a helper method like so
```
export const checkValidityOnElement =
    /* istanbul ignore next */
    (element) => element.checkValidity();
```
Now in my component I import this helper function to perform the validation.  So now in my unit test I can simply stub out this helper method in the usual way.
This does mean the actual `checkValidity` is untested in the helper file, but it's just a simple one-liner it's probably same to be left untested (hence the ignore next statement)
