### ISSUE TITLE
Can't get state of component wrapped in HOC

### ISSUE THREAD

**Issue by matthewgertner** [airbnb/enzyme#431]
I have a component wrapped in an HOC. I'm mainly interested in testing the inner component, but I'm finding it difficult to do things like access its state since the root component of the wrapper is the HOC. Do I have to export a separate unwrapped version of the component for testing? What is the justification for not exposing state on non-root components?

**Comment by matthewgertner** [comment]
Stumbled on https://github.com/airbnb/enzyme/issues/98. Looks like you are doing the same thing I ended up doing (i.e. exporting the unwrapped version as well). I'll close this but IMO it would be interesting to be able to access the state of the wrapped component since then I would really be testing the same thing that is used in the real app (i.e. the HOC wrapper).

**Comment by ljharb** [comment]
I don't think this is something React itself exposes.

**Comment by kokill** [comment]
@CosticaPuntaru @matthewgertner this worked for me.
const wrapper = shallow(component, { context: { /* pass context if required */}}); // decorated component
const child = shallow(wrapper.get(0)); // pure component

**Comment by matthewgertner** [comment]
@ljharb Not sure I follow. Isn't `state` just a normal property of the component?

**Comment by matthewgertner** [comment]
@kokill I need to use `mount` since my tests rely on lifecycle methods.

**Comment by ljharb** [comment]
@matthewgertner yes but of the *wrapper* component. I don't think you can get at the *wrapped* component's state.

**Comment by Aweary** [comment]
It's usually better to do bottom up (leaf nodes to root) instead of top down testing anyways. You should test your presentational (or whatever sits at the bottom of your component tree) components, mocking any props that they require. Then move up the tree and do the same for their parent components. 

This is why shallow rendering is so popular. Reaching down into the component tree to validate deep child state is confusing (and difficult as @ljharb mentions). If you validate in isolation at each level then you get an implied contract that the entire tree should render as expected.

For components wrapped in HOCs we usually recommend exporting the unwrapped component and mocking any props that the HOC is providing. If you want to test the HOC itself you are allowed to query props on a child component, which should be enough if you're using composition.

**Comment by matthewgertner** [comment]
Fair enough, that's the approach I ended up taking and it looks good so far. Thanks!

**Comment by dabit1** [comment]
I finally found a very good solution to get a wrapper from a decorated component. For shallowed components you can use `dive()` but there is no similar method for mounted components. This is the solution I did:

```javascript
const wrapper = mount(shallow(<MyComponent />).get(0))
```

Works like a charm :)

**Comment by jstray** [comment]
I'm having this issue too. I have to wrap the component under test to provide the context:
```
      wrapper = mount(
        <DragDropContextProvider>
          <MyComponent>
        </DragDropContextProvider>);
```

MyComponent will not mount if it's not wrapped, but I need to get its state to test certain things. That state clearly exists somewhere, because MyComponent is running as expected in the rest of the tests, but I can't get at it.

**Comment by espadaAD** [comment]
I can confirm that @dabit1 solution works. Unfortunately, in my circumstance, my company requires us to use javascript decorators, so I can't export the base component for testing.

**Comment by mgerring** [comment]
Hi @dabit1 , it's not clear to me what `<MyComponent />` is in this example.

I have a component that looks something like this in the test:

```
<Provider store={mockStore}>
  <MyComponent ...props></MyComponent>
</Provider>
```

I attempted to use what I thought your solution was suggesting:

```
wrapper = mount(shallow(
<Provider store={mockStore}>
  <MyComponent ...props></MyComponent>
</Provider>
).get(0))
```

...and wound up with the same error I had before I was wrapping the component with `Provider`. Am I missing something here?

**Comment by dabit1** [comment]
@mgerring My solution is for decorated components. Is your component decorated? If not, I think just with mount() should works:

```javascript
mount(
  <Provider store={mockStore}>
    <MyComponent ...props></MyComponent>
  </Provider>
)
```

**Comment by AntonioRedondo** [comment]
@dabit1 I have the same very issue with the example you show. `shallow()` cannot be used in my test. How do you access the state of `MyComponent`?

**Comment by dabit1** [comment]
@AntonioRedondo can you show me your test?

**Comment by AntonioRedondo** [comment]
It's exactly like the example you put three comments above.

As @mgerring says, it looks like there is no way to get the state of a component when using `mount()` if it's not the root. And this is an issue when `<Provider>` is used as root.

If I call `.state()` on anything apart the root I receive the error: `ReactWrapper::state() can only be called on the root`. And `.dive()` can only be called on shallowed rendered components, thing that I cannot use because the test is huge and it would break rest of dozens of tests.

**Comment by dabit1** [comment]
@AntonioRedondo so in my first comment you will find the solution. You have to mount a react element from shallowed component.

**Comment by swashata** [comment]
For a decorative HOC (while using [react-jss](https://github.com/cssinjs/react-jss)), this is the solution I am using

**Foo.jsx**
```jsx
import React from 'react';
import injectSheet from 'react-jss';
const styles = ({ color }) => ({
    styled: {
        background: color.bg,
        color: color.fg,
    }
});

class Foo extends React.Component {
    state = {
        foo: 'Foo',
    };

    render() {
        <div className=`foo ${props.classes.styled}`>Foo</div>
    }
}

export injectSheet(styles)(Foo);
```

**Foo.spec.jsx**
```js
// import react, enzyme etc
import Foo from 'Elements/Foo';
import { ThemeProvider } from 'react-jss';
const wrapper = mount(
    <ThemeProvider theme={{ color: { bg: '#000000', fg: '#ffffff' } }}>
        <Foo />
    </ThemeProvider>
);
const componentInstance = wrapper
    .childAt(0) // could also be .find(Foo)
    .instance();

// do testing with componentInstance.state.something or componentInstance.props.something
test('something', () => {
    expect(componentInstance.state.foo).toBe('Foo');
});
```

I hope it helps.

**Comment by AGMETEOR** [comment]
shallow(<MyComponent.WrappedComponent) {...props} />)
