### ISSUE TITLE
Remove a property from render

### ISSUE THREAD

**Issue by diegohaz** [airbnb/enzyme#485]
My component uses [Radium](https://github.com/FormidableLabs/radium) and I'm trying to test it with `shallow`, but it's throwing some errors like the need for `<StyleRoot>` and others.

The point is that all these errors would go away if `shallow` ignores the `style` attribute when rendering the component.

**Is there a way to omit some property when rendering a component using `shallow`?**

**Comment by Aweary** [comment]
You can either mock the props/context that `<StyleRoot/>` may be providing, or export your unwrapped component alongside the one wrapped without the `radium` higher order component (if you're using it)

I think mocking is a better alternative than allowing props to be ignored, which I don't even think we'd be able to do. We'd have to just somehow mock them internally since we can't hook into your `render` method and that would be ineffective.
