### ISSUE TITLE
Document the API

### ISSUE THREAD

**Issue by hakunin** [airbnb/enzyme#498]
Hey guys,
Enzyme seems a bit lacking API documentation.

For instance, how do I get the component from the wrapper?

If you could just generate an API doc and link to it, that would be fantastic.

**Comment by Aweary** [comment]
Hey @hakunin, thanks for the issue. We have docs available at http://airbnb.io/enzyme. It's a rather comprhensive API reference.

> For instance, how do I get the component from the wrapper?

If you're looking for the instance of your component you can use `instance()` which is documented here: http://airbnb.io/enzyme/docs/api/ReactWrapper/instance.html

If you're looking to get a wrapper for a child component rendered by your root wrapper you can use `find()` which is documented here: http://airbnb.io/enzyme/docs/api/ReactWrapper/find.html

Since we already do have an API doc, I'm going to close this out since there's nothing actionable for us. If you have any usage questions, feel free to ask!
