### ISSUE TITLE
Jasmine support

### ISSUE THREAD

**Issue by just-boris** [airbnb/enzyme#55]
As it follows from the docs

> Reagent is unopinionated regarding which test runner or assertion library you use, and should be compatible with all major test runners and assertion libraries out there.

I tried to use it with Jasmine and it worked fine until I tried to use `mount`. I got the error.

```
TypeError: before is not a function
```

`before` hook is the Mocha-specific thing, Jasmine has the similar thing named `beforeAll`.

Thanks for the awesome tool! It is really missing piece to my tests, but I can't use it due to lack of Jasmine support.

**Comment by lelandrichardson** [comment]
@just-boris thanks for bringing this up. Can you post the code that is actually causing this to throw?

There are a couple of assumptions made in the library about mocha being present, however these are mostly undocumented features which are used internally at Airbnb but will likely be removed.

Running `mount()` on it's own should not be requiring a `before` function being present. The only thing I can find that would, actually, is the `useSetStateHack()` export?

I could be missing something though. A stack trace would be helpful.

**Comment by just-boris** [comment]
The error has been caused by `describeWithDOM`. This is my usage example: 

```
describeWithDOM('<Component />', function() {
    it('should be rendered without errors', function() {
        const component = mount(<Component />)
    })
});
```

The `describeWithDOM` is necessary wrapper to use `mount`, as it follows from docs.

**Comment by lelandrichardson** [comment]
@just-boris I see.  I think we should make some documentation changes to more accurately reflect what is necessary. There is a good chance that `describeWithDOM` will be removed from the library in a later release, as it is definitely mocha specific.

In order to use `mount`, you need only to have DOM API's present in the global scope.  If you would like to use `jsdom`, as long as you have the DOM loaded in the global scope when you make the call to `mount()`, everything should work.

the `describeWithDOM` function is used in conjunction with mocha for two reasons:

1. It re-instantiates a new DOM before every test so that tests don't have any side effects on other tests
2. It automatically skips the test if it is being run in an environment where `jsdom` cannot be loaded (ie, node < 4).

If you're running the tests in an environment with DOM API's, `mount` should "just work" without the use of `describeWithDOM`.

Let me know if that makes sense?

**Comment by just-boris** [comment]
Yes, I can set up jsdom by myself and it seems to be working. 

But `desctibeWithDOM` is very nice, it doesn't require a lot of setup frictions, it just works. As far as I see, the issue is that `describeWithDOM` relied on `mocha-jsdom`. So, if I want to make it work with jasmine, I can make similar module `jasmine-jsdom`. By the way, the name is free and I am going to take it.

**Comment by lelandrichardson** [comment]
@just-boris there is some discussion about creating additional test-runner-specific modules like `mocha-reagent` and `karma-reagent`, etc. that would have some of these conveniences built-in.  `describeWithDOM` may get graduated to such a library, and retired here.
