### ISSUE TITLE
Add static typings with flow

### ISSUE THREAD

**Issue by aweary** [airbnb/enzyme#575]
How do you guys feel about using flow typing to the codebase? We can do it gradually like they're doing with React right now. It should give us a better developer experience and might even catch some subtle bugs we have in the codebase right now.

I'd be happy to work on it 👍 

cc @ljharb @blainekasten @nfcampos @lelandrichardson

**Comment by ljharb** [comment]
I'm a big -1 on this at the moment. The flow UX and CLI tooling is simply not ready for a "not Facebook" or "not monorepo" experience imo - Airbnb is not yet using Flow for this reason, and enzyme should continue to follow our internal Airbnb styles.

When the Flow team has had time to respond to and implement the feedback they've been given, I'm confident the tooling will be good enough that we can adopt it on all our projects.

---

Separately, I'm very skeptical that adding a type system will add meaningful value. The class of bugs that type systems solve are such a tiny fraction of the actual bugs that happen in JS, and eslint + unit tests covers virtually all of them anyways. I don't think adding types will *hurt*, of course - I just don't think it's going to add enough value to warrant the complexity.

**Comment by Aweary** [comment]
> The flow UX and CLI tooling is simply not ready for a "not Facebook" or "not monorepo" experience imo

FWIW I've personally used flow in a few projects of varying complexity and I've found that the utility justified the complexity in most cases. Could you expand on what specifically you feel makes flow difficult to use as far as UX and CLI tooling goes? 

The developer experience for me has usually been pretty good, but I do use Nuclide which has particularly good flow support, so I may have a skewed perspective on current tooling.

> enzyme should continue to follow our internal Airbnb styles.

Understandable, I totally respect that.

> When the Flow team has had time to respond to and implement the feedback they've been given, I'm confident the tooling will be good enough that we can adopt it on all our projects.

Do you have a point of reference I can use for the feedback you've provided? I'd like to track progress in those areas to see when/if flow becomes a viable option here.

>Separately, I'm very skeptical that adding a type system will add meaningful value. The class of bugs that type systems solve are such a tiny fraction of the actual bugs that happen in JS, and eslint + unit tests covers virtually all of them anyways.

Hmm, I'm torn on this. I think the value proposition of flow is pretty good; linting has limited utility when it comes to application logic and a test suite can often have difficult to spot coverage holes (I know we've seen this a couple times recently with enzyme). 

> I don't think adding types will hurt, of course - I just don't think it's going to add enough value to warrant the complexity.

What kind of complexity are you specifically worried about? As far as implementation goes, you do pay the complexity cost of adding new syntax and a new abstraction layer. But that's partially offset by gradual typing and, IMO, flow has a relatively intuitive syntax in most cases.

Otherwise, it shouldn't add any complexity as far as code structure or logic flow goes.

____

Anyways, if you guys ever do want to give flow a try I would say testing it out on an OS project is probably one of the more painless integration strategies.

**Comment by stereobooster** [comment]
Flow for me:
- Often broken in MacOS X (`The flow server is not responding (0 retries remaining)`). Should I try to use it inside linux (docker or Vagrant)?
- Scans all node_modules which is very slow 
- No way to debug type signatures. I wrote types for Downshift, but it didn't work as I expected and I had no clue why. I fixed original issue by reading a lot of other type signatures and experimenting. I failed to find proper documentation. I asked for help in chat room and there were no response. Current issue - type signatures work, but type checking is very slow even though there are only 89 files in the project, I assume constraint solver gets into the loop somewhere, but I have no idea how to debug it.

See also https://github.com/stereobooster/type-o-rama/issues/3

I respect Flow authors, but it is a lot of struggle to use Flow. It is require a lot of work until Flow will be comfortable to use.

**Comment by aweary** [comment]
Flow is pretty consistently stable for me, you can ignore `node_modules`, and I don't find myself needing to debug type signatures frequently.

With that said, flow does still have it's problems, but I think there's still value in static typings for Enzyme. Flow or TypeScript, doesn't matter to me at this point.
