### ISSUE TITLE
Set value to Input Text 

### ISSUE THREAD

**Issue by Kamaraju333** [airbnb/enzyme#665]
I know this is a duplicate one , but unable to set the value below is the example 
```jsx
<div>
  <FormControl type"input" ref="exampleName"/><Button onClick={this.handleClick}/>
</div>

handleClick = () => {
  const ExampleName=ReactDom.findDOMNode(this.refs.exampleName).value.trim()
  if(ExampleName){
    doSomeThing.......
  }

}
```

In the above scenario how do i set value to my FormControl/input to test the doSomething ...

Any help is appreciated

**Comment by laumair** [comment]
@Kamaraju333 Any particular reason you are using `refs` instead of simple `onChange`? I would definitely recommend to pass callbacks to children for something like this. And just so that you know you've put ref on a composite component here.

**Comment by Kamaraju333** [comment]
@laumair Basically i need to capture the value entered in the textbox , everything happens on the click  of the button so the call backs i have on click of button . Is there way to get the input value with out any action ?

**Comment by laumair** [comment]
@Kamaraju333 Can you post a snippet of how your `FormControl` component looks like?

**Comment by Kamaraju333** [comment]
@laumair FormControl is from https://react-bootstrap.github.io/components.html#forms

**Comment by laumair** [comment]
@Kamaraju333 `<FormControl ref={(c) => this._input = c}` 
`this._input.value` would give you the value I think. 

I haven't tested this and haven't used `react-bootstrap` but just a quick skim over the docs, I think this should work with your use case. 

> 
_ The <FormControl> component directly renders the <input> or other specified component. If you need to access the value of an uncontrolled <FormControl>, attach a ref to it as you would with an uncontrolled input, then call ReactDOM.findDOMNode(ref) to get the DOM node. You can then interact with that node as you would with any other uncontrolled input. If your application contains a large number of form groups, we recommend building a higher-level component encapsulating a complete field group that renders the label, the control, and any other necessary components. We don't provide this out-of-the-box, because the composition of those field groups is too specific to an individual application to admit a good one-size-fits-all solution._
