### ISSUE TITLE
react-addons-test-utils is not in devDependencies for enzyme

### ISSUE THREAD

**Issue by gogocurtis** [airbnb/enzyme#746]
If one is using jest and then one installs enzyme with yarn, 'react-addons-test-utils' is attempted to be imported by enzyme - only nothing has asked that it be installed. The work around is to install.

Because of this I think 'react-addons-test-utils' should be a dependency of enzyme.

**Comment by blainekasten** [comment]
There is a specific reason for this. It is like this because we support multiple versions of React and the react-addons-test-utils is only needed for React 14+. Since it's version dependent, package.json doesn't work for this. This will be properly solved when we sort out the future plans] for enzyme. #742
