### ISSUE TITLE
setProps/setState/setContext naming issue

### ISSUE THREAD

**Issue by webOS101** [airbnb/enzyme#763]
As currently implemented, `setProps`, `setState`, and `setContext` do not do what their names imply.  They do not set the argument as the new value but instead merge the new value with existing ones.  I see the utility in this and it makes sense to do that, however...  The name implies a replacement, not a merge.  Worse, the short docs (e.g. https://github.com/airbnb/enzyme/blob/master/docs/api/mount.md#setstatenextstate--reactwrapper) do not mention the merge behavior.  A clearer prefix might be `merge` rather than `set`. 

Given that this API is fairly broadly used I don't see any reasonable way to handle this.  I'm not even sure if there's utility in having versions that did completely replace the existing value (perhaps `replaceProps`, etc.?).  In any case, I'm throwing this out for discussion.

**Comment by ljharb** [comment]
The names come from React, which uses `setState` - I think that understanding that "setX merges instead of replaces" is just one of those things that new React users have to learn.

If React changes the names of these API methods, then it would be quite appropriate for enzyme to do so - but until then, it would be quite inappropriate for enzyme to deviate from React.
