### ISSUE TITLE
simulate example doesn't make sense, nor does it work

### ISSUE THREAD

**Issue by alex-wilmer** [airbnb/enzyme#88]
http://airbnb.io/enzyme/docs/api/ShallowWrapper/simulate.html

I'm trying to get a grip on how to test my React components. Specifically, I feel like a proper test would be to assert some state, call a function that calls `setState`, and re-assert the state. The below example uses an inline function, which confuses me more.. is there no such possibility to directly call the function without "simulating" an event? Furthermore, the simulate example in the docs doesn't seem to make sense:

```
class Foo extends React.Component {
  constructor(props) {
    super(props);
    this.state = { count: 0 };
  }
  render() {
    const { count } = this.state;
    return (
      <div>
        <div className={`clicks-${count}`}>
          {count} clicks
        </div>
        <a onClick={() => this.setState({ count: count + 1 })}>
          Increment
        </a>
      </div>
    );
  }
}

const wrapper = shallow(<Foo />);

expect(wrapper.find('.clicks-0').length).to.equal(1);
wrapper.simulate('click');
expect(wrapper.find('.clicks-1').length).to.equal(1);
```

I don't understand `simulate('click')` here.. doesn't it need to find the anchor tag first to click it?

**Comment by ljharb** [comment]
This seems like the example is just off - `wrapper.find('a').simulate('click')` seems like the right thing to do here.

In this case, since the `onClick` handler is recreated on every render, no other reference to it exists, so simulating the click seems like it'd be the only way to invoke it. An alternative would be creating an autobound instance method, and setting that as the `onClick` handler - but then your tests would need to have more intimate knowledge of your implementation in order to invoke it directly, which makes for a more brittle test.
