### ISSUE TITLE
react-test-renderer should be a dependency

### ISSUE THREAD

**Issue by dzearing** [airbnb/enzyme#905]
Having documentation say to add react-test-renderer dependency in addition to enzyme defeats the purpose of npm dependencies. 

Couldn't this package be a dependency of enzyme so that you just install enzyme and get what it needs as well?

Alternatively, if there is some reason why this is bad, why not have a peer dependency so that at a minimum you get an install warning rather than a mysterious build error about react-test-renderer missing?

**Comment by ljharb** [comment]
Because the dependency only applies when you're using React 15.5+.

Using any of npm's dependency features would force everyone using any version of React to have the dependencies for all of them.

Eventually we'll be reworking enzyme to use an adapter pattern, so you'd include the adapter for the React version you needed, and it would just have normal dependencies/peerDependencies.

This is mentioned in the [readme](https://github.com/airbnb/enzyme#installation).

**Comment by dzearing** [comment]
@ljharb but would it hurt react 15.4 users if the dependency was included? Basically you could avoid the consumers doing the extra unexpected step...

**Comment by ljharb** [comment]
Because of the multiple conditional version ranges (that would easily become incompatible), I think it would cause far more problems than it solved.
