### ISSUE TITLE
fix and re-enable failing examples

### ISSUE THREAD

**Issue by ljharb** [airbnb/enzyme#965]
The mocha, karma, and react-native examples are currently failing tests.

These need to be fixed, and re-enabled - ASAP.

**Comment by mikeaustin** [comment]
Looks like the enzyme-example-mocha example is using the old API? FYI, learning Mocha and enzyme has been so difficult because of API non-backwards compatibility in other libraries such as jsdom.

This project is from a direct link from enzyme:
https://github.com/airbnb/enzyme/blob/master/docs/guides/jsdom.md

The example project:
https://github.com/lelandrichardson/enzyme-example-mocha

**Comment by jsmey** [comment]
I submitted a PR to fix the enzyme-example-mocha tests
https://github.com/lelandrichardson/enzyme-example-mocha/pull/12

**Comment by lelandrichardson** [comment]
I would like to deprecate these example repos and move them into this repo if possible? I think the way we were running these tests was pretty hacky, and I also think that because they were separate repos that they never got any attention and got out of date too quickly. Keeping them in here in the packages directory seems ideal to me.

**Comment by jsmey** [comment]
ok, I can start on the mocha example

**Comment by ljharb** [comment]
The example now lives in this repo.
